### ISSUE TITLE
Conflict with Cooking for Blockheads

### ISSUE THREAD

**Issue by murilorodelli** [Oethever/RealisticStorage#1]
Hi. I've found a bug with Cooking for blockheads, on recipe table. This is the log

[14:15:49] [Server thread/INFO]: Container name: net.blay09.mods.cookingforblockheads.container.ContainerRecipeBook
[14:15:49] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerContainerEvent$Close@13133473:
java.lang.NullPointerException: null
	at oethever.realisticstorage.containerguard.ContainerGuard.getSlots(ContainerGuard.java:130) ~[ContainerGuard.class:1.2.1]
	at oethever.realisticstorage.containerguard.ContainerGuard.onInventoryClose(ContainerGuard.java:49) ~[ContainerGuard.class:1.2.1]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_ContainerGuard_onInventoryClose_Close.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.closeContainer(EntityPlayerMP.java:1023) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processCloseWindow(NetHandlerPlayServer.java:1139) [pa.class:?]
	at net.minecraft.network.play.client.CPacketCloseWindow.processPacket(SourceFile:20) [lg.class:?]
	at net.minecraft.network.play.client.CPacketCloseWindow.processPacket(SourceFile:8) [lg.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.runTask(Util.java:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[14:15:49] [Server thread/ERROR]: Index: 3 Listeners:
[14:15:49] [Server thread/ERROR]: 0: NORMAL
[14:15:49] [Server thread/ERROR]: 1: ASM: tschipp.carryon.common.capabilities.event.PositionClientEvents@1241c5b2 onGuiClose(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Close;)V
[14:15:49] [Server thread/ERROR]: 2: ASM: crafttweaker.mc1120.events.CommonEventHandler@1d7e8222 onPlayerCloseContainer(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Close;)V
[14:15:49] [Server thread/ERROR]: 3: ASM: oethever.realisticstorage.containerguard.ContainerGuard@53e079d4 onInventoryClose(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Close;)V
[14:15:49] [Server thread/ERROR]: 4: ASM: com.zeitheron.visuals.proxy.ClientProxy@784b0d0c closeContainer(Lnet/minecraftforge/event/entity/player/PlayerContainerEvent$Close;)V
[14:15:49] [Server thread/WARN]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_ContainerGuard_onInventoryClose_Close (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_ContainerGuard_onInventoryClose_Close)
[14:15:49] [Server thread/FATAL]: Minecraft ran into a problem! Report saved to: C:\Games\Minecraft\Instances\BasePack\crash-reports\crash-2020-08-15_14.15.49-server.txt
---- Minecraft Crash Report ----
// Don't do that.

Time: 2020-08-15 14:15:49 BRT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at oethever.realisticstorage.containerguard.ContainerGuard.getSlots(ContainerGuard.java:130)
    at oethever.realisticstorage.containerguard.ContainerGuard.onInventoryClose(ContainerGuard.java:49)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_960_ContainerGuard_onInventoryClose_Close.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.entity.player.EntityPlayerMP.closeContainer(EntityPlayerMP.java:1023)
    at net.minecraft.network.NetHandlerPlayServer.processCloseWindow(NetHandlerPlayServer.java:1139)
    at net.minecraft.network.play.client.CPacketCloseWindow.processPacket(SourceFile:20)
    at net.minecraft.network.play.client.CPacketCloseWindow.processPacket(SourceFile:8)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

**Comment by Oethever** [comment]
Thanks for the report, I'll have a look at it.

**Comment by Oethever** [comment]
Minecraft version 1.18 is now the supported version.
